#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width 2
bspc config window_gap 2

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

exec qt5ct &
exec picom --config ~/.config/picom/picom.conf &
exec xclip &
exec polybar &
exec nm-applet >/dev/null 2>&1 &
exec xsetroot -cursor_name left_ptr &
exec /home/hcj/.fehbg &
exec xset r rate 250 45 &
exec xinput set-prop "VEN_04F3:00 04F3:311C Touchpad" "libinput Natural Scrolling Enabled Default" 1
