[bar/main]
width = 100%
height = 24pt
radius = 6

dpi = 96

line-size = 9pt

border-size = 4pt
border-color = #000000

font-0 = "JetBrainsMono Nerd Font:size=12"
modules-left = bspwm
modules-center = windowtitle
modules-right = pulseaudio clock systray
monitor = ${env:MONITOR:}

; Appearance
background = #222222
foreground = #dfdfdf

padding-left = 0
padding-right = 1

module-margin = 1
enable-ipc = true

; Separator between desktops
separator = |

[settings]
screenchange-reload = true

[module/bspwm]
type = internal/bspwm


enable-click = true
enable-scroll = false
pin-workspaces = false

; Only show workspaces with open windows
label-empty =

; Focused desktop
label-focused = %index%
label-focused-padding = 1
label-focused-background = #44475a
label-focused-foreground = #f8f8f2

; Occupied desktops
label-occupied = %index%
label-occupied-padding = 1
label-occupied-foreground = #bbbbbb

; Urgent desktops
label-urgent = %index% !
label-urgent-padding = 1
label-urgent-background = #ff5555
label-urgent-foreground = #ffffff


[module/windowtitle]
type = custom/script
exec = ~/.config/polybar/scripts/window-title.sh
tail = true
interval = 1

[module/clock]
type = internal/date
interval = 1
date = %a %d %b
time = %I:%M %p
label = %date% %time%

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-prefix-foreground = #dfdfdf
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = #222222


[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt
tray-position = right
tray-maxsize = 16pt
